spring:
  application:
    name: Server Default
  datasource:
    url: jdbc:mariadb://localhost:3306/users
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    session:
      timeout: 1m
